### ISSUE TITLE
[EXPIRED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [vasuman/FiSH#1]
Dear Mr. Ravichandran,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows w/o Python?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by vasuman** [comment]
Hi, sorry for the delay. I've configured cx_freeze in the setup.py and remember generating the Windows binary a while back but I seem to have forgotten to upload and link it here. Unfortunately, I no longer have access to a Windows machine

**Comment by sergeevabc** [comment]
@vasuman, did you get a chance to look into this more thoroughly?
